name: Sync Repo Description

on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: zhengbangbo/update-repository-description@main
        with:
          repo-token: ${{ secrets.REPO_TOKEN }}